#! /bin/sh

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

bspc config split_ratio         0.52
bspc config border_width        4
bspc config window_gap          20
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config top_padding 14

# colors
bspc config normal_border_color "#101010"
bspc config focused_border_color "#1f1f1f"

panel &
