#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# music player daemon
mpd &

# set wallpaper
feh --bg-fill ~/images/wallpaper/9ncYySC.jpg &

# X settings
xrdb -override ~/.Xresources & 

# start low battery notification daemon
battery-thingy 15 "mpv '/home/tobias/videos/Meshuggah - Bleed 8-bit-5PJ3fGMgGgY.flv'" 30 BAT0  &

# shortcuts 
sxhkd &

# automount
devmon --exec-on-drive 'open-mount "%d" "%f" "%l"' &

# set the cursor
xsetroot -cursor_name left_ptr

# start remind daemon
#remind '-kecho REM%s > $PANEL_FIFO' -z .reminders &

# start gpg-agent
eval $(gpg-agent --daemon) &

# set wm name for compitability reasons
wmname LG3D &

# don't use HDMI for sound
pactl set-card-profile 0 output:analog-stereo+input:analog-stereo

# custom keyboard settings
xmodmap /home/tobias/.xmodmap &

# start the window manager
exec herbstluftwm
