#!/bin/sh
# initialize user session
#systemd --user &

# set wallpaper
feh --bg-scale ~/Downloads/tf2_wallpaper/wallpaper-905577_smaller.jpg &

# X settings
xrdb -override ~/.Xresources & 

# set the keyboard map
setxkbmap de &

# shortcuts
sxhkd &

# set the screensaver
xss slock &

# automount
devmon   &

# Music Player Daemon
mpd &

# mpdscribble daemon
mpdscribble -D &

# when to start the screensaver
xset s 900 & # sec

# set ls colors
eval `dircolors -b ~/.dircolors.custom` 

# custom keyboard settings
xmodmap ~/.xmodmap

# set the cursor
xsetroot -cursor_name left_ptr

# watch the maildirs for changes and write them to a file
/home/tobias/bin/cwatch -e create,delete -n -r -d /home/tobias/mail/ -c "/home/tobias/bin/countMail.py > /home/tobias/mail/.count" &

# count the new mails 
/home/tobias/bin/countMail.py > /home/tobias/mail/.count &

# start the window manager
exec xmonad
