#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# monitor settings
out=$(xrandr)
if [[ $out == *HDMI* ]]
then
    xrandr --output LVDS1 --off
fi

# enable compositing
compton -cCGfF -o 0.38 -O 200 -I 200 -t 0.02 -l 0.02 -r 3.2 -D2 -m 0.88 &

# set wallpaper
feh --bg-fill ~/images/wallpaper/wallpaper-59928.png &

# X settings
xrdb -override ~/.Xresources & 

# shortcuts 
sxhkd &

# set the screensaver
xss physlock &

# music player daemon
mpd &

# automount
devmon &

# when to start the screensaver
xset s 900 & # sec

# set the cursor
xsetroot -cursor_name left_ptr

# start remind daemon
remind '-kecho REM%s > $PANEL_FIFO' -z .reminders &

# count the new mails 
/home/tobias/bin/countMail.py > /home/tobias/mail/.count &

# start gpg-agent
eval $(gpg-agent --daemon) &

# set wm name for compitability reasons
wmname LG3D &

# don't use HDMI for sound
pactl set-card-profile 0 output:analog-stereo+input:analog-stereo

# create new PANEL_FIFO
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# custom keyboard settings
xmodmap /home/tobias/.xmodmap &

# start the window manager
exec bspwm -s "$PANEL_FIFO" -p W
